/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-pages': ProductPage;
    'landing-pages': LandingPage;
    'faq-items': FaqItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-pages': ProductPagesSelect<false> | ProductPagesSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-pages".
 */
export interface ProductPage {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  medusaProductId: string;
  handle: string;
  syncStatus: 'active' | 'deleted';
  /**
   * 这部分由 Medusa 自动同步，用于帮助内容编辑识别商品。
   */
  medusaSummary?: {
    productTitle?: string | null;
    subtitle?: string | null;
    thumbnail?: string | null;
    productStatus?: string | null;
    collectionTitle?: string | null;
    tags?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  sections?:
    | (
        | {
            title?: string | null;
            items?:
              | {
                  label: string;
                  anchorId: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section-nav';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            headline: string;
            subheadline?: string | null;
            mediaType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: (number | null) | Media;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefit-strip';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            supportingText?: string | null;
            imagePosition?: ('left' | 'right') | null;
            showImage?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'commerce-callout';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            title?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stat-strip';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feature-grid';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            title: string;
            body: string;
            mediaPosition?: ('left' | 'right') | null;
            media: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media-story';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            leftColumnLabel: string;
            rightColumnLabel: string;
            rows?:
              | {
                  feature: string;
                  leftValue: string;
                  rightValue: string;
                  emphasis?: ('none' | 'left' | 'right') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison-table';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  /**
                   * 填写 Medusa 商品 handle，例如 remarkable-paper-pro。
                   */
                  productHandle: string;
                  badge?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'product-shelf';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            bundles?:
              | {
                  /**
                   * 填写 Medusa 商品 handle，例如 remarkable-paper-pro-bundle。
                   */
                  productHandle: string;
                  badge?: string | null;
                  highlight?: string | null;
                  description?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bundle-grid';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            quote: string;
            author: string;
            role?: string | null;
            avatar?: (number | null) | Media;
            highlight?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote-showcase';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            rows?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spec-table';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            description?: string | null;
            groups?:
              | {
                  title: string;
                  description?: string | null;
                  items?:
                    | {
                        question: string;
                        answer: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq-groups';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title: string;
            description?: string | null;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  sections?:
    | (
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            headline: string;
            subheadline?: string | null;
            mediaType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: (number | null) | Media;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feature-grid';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            eyebrow?: string | null;
            title: string;
            body: string;
            mediaPosition?: ('left' | 'right') | null;
            media: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media-story';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            rows?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spec-table';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * 可选，用于页面内锚点导航，例如 writing-experience。
             */
            anchorId?: string | null;
            title: string;
            description?: string | null;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  productHandle?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-pages';
        value: number | ProductPage;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-pages_select".
 */
export interface ProductPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  medusaProductId?: T;
  handle?: T;
  syncStatus?: T;
  medusaSummary?:
    | T
    | {
        productTitle?: T;
        subtitle?: T;
        thumbnail?: T;
        productStatus?: T;
        collectionTitle?: T;
        tags?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  sections?:
    | T
    | {
        'section-nav'?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    anchorId?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              mediaType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'benefit-strip'?:
          | T
          | {
              anchorId?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'commerce-callout'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              supportingText?: T;
              imagePosition?: T;
              showImage?: T;
              id?: T;
              blockName?: T;
            };
        'stat-strip'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'feature-grid'?:
          | T
          | {
              anchorId?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'media-story'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              title?: T;
              body?: T;
              mediaPosition?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        'comparison-table'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              leftColumnLabel?: T;
              rightColumnLabel?: T;
              rows?:
                | T
                | {
                    feature?: T;
                    leftValue?: T;
                    rightValue?: T;
                    emphasis?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'product-shelf'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    productHandle?: T;
                    badge?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bundle-grid'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              bundles?:
                | T
                | {
                    productHandle?: T;
                    badge?: T;
                    highlight?: T;
                    description?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'quote-showcase'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              quote?: T;
              author?: T;
              role?: T;
              avatar?: T;
              highlight?: T;
              id?: T;
              blockName?: T;
            };
        'spec-table'?:
          | T
          | {
              anchorId?: T;
              title?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'faq-groups'?:
          | T
          | {
              anchorId?: T;
              title?: T;
              description?: T;
              groups?:
                | T
                | {
                    title?: T;
                    description?: T;
                    items?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              anchorId?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              anchorId?: T;
              title?: T;
              description?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              mediaType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'feature-grid'?:
          | T
          | {
              anchorId?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'media-story'?:
          | T
          | {
              anchorId?: T;
              eyebrow?: T;
              title?: T;
              body?: T;
              mediaPosition?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        'spec-table'?:
          | T
          | {
              anchorId?: T;
              title?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              anchorId?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              anchorId?: T;
              title?: T;
              description?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  productHandle?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}